"""CriticHumanLike class for distinguishing human vs generated utterances."""

from typing import Literal

from pydantic import BaseModel

from autointent.generation import Generator
from autointent.generation.chat_templates import Message, Role


class CriticResponse(BaseModel):
    """Structured answer."""
    reasoning: str
    label: Literal["human", "generated"]
    explanation: str

class CriticHumanLike:
    """A simple critic class that classifies user utterances as either 'human' or 'generated'.

    using an LLM-based binary classifier prompt.
    """

    def __init__(self, generator: Generator)-> None:
        """Initialize the CriticFirst.

        Args:
            generator: Wrapper for the LLM API to generate classification responses.
        """
        self.generator = generator

    def build_classification_prompt(self, example: str, intent_name: str) -> Message:
        """Args.

            example: The user utterance to classify.
            intent_name: The name of the intent associated with the utterance.

        Returns:
            Message: A formatted message prompt for classification.
        """
        content = (
            "You are a critic that determines whether a user utterance was written by a human or "
            "generated by a language model.\n\n"
            f"Intent: {intent_name}\n"
            f'Utterance: "{example}"\n\n'
            "Respond in **JSON format** with three keys:\n"
            "- `reasoning`: a short chain-of-thought where you explain your logic\n"
            "- `label`: must be either `human` or `generated`\n"
            "- `explanation`: a concise summary of your decision\n\n"
            "Example:\n"
            "{\n"
            '  "reasoning": "The phrasing includes casual contractions and natural hesitation. The utterance '
            'flows similarly to how a human would speak spontaneously.",\n'
            '  "label": "human",\n'
            '  "explanation": "The utterance includes natural hesitation and informal phrasing '
            'typical of human speech."\n'
            "}"
        )
        return Message(role=Role.USER, content=content)

    def is_human(self, utterance: str, intent_name: str) -> bool:
        """Args.

            utterance: The utterance to evaluate.
            intent_name: The associated intent.

        Returns:
            bool: True if classified as human, False otherwise.
        """
        messages = self.build_classification_prompt(utterance, intent_name)
        response: CriticResponse = self.generator.get_structured_output_sync(
        messages=messages,
        output_model=CriticResponse,
        max_retries=3)
        return response.label == "human"
