"""CriticHumanLike class for distinguishing human vs generated utterances."""
from __future__ import annotations

from typing import TYPE_CHECKING, Literal

from pydantic import BaseModel

from autointent.generation.chat_templates import Message, Role

if TYPE_CHECKING:
    from autointent.generation import Generator


class CriticResponse(BaseModel):
    """Structured answer."""

    reasoning: str
    label: Literal["human", "generated"]


class CriticHumanLike:
    """A simple critic class that classifies user utterances as either 'human' or 'generated'.

    using an LLM-based binary classifier prompt.
    """

    def __init__(self, generator: Generator, max_retries: int = 3) -> None:
        """Initialize the CriticFirst.

        Args:
            generator: Wrapper for the LLM API to generate classification responses.
            max_retries: Maximum number of attempts to retry classification if the response is invalid.
        """
        self.generator = generator
        self.max_retries = max_retries

    def build_classification_prompt(self, example: str, intent_name: str) -> Message:
        """Args.

            example: The user utterance to classify.
            intent_name: The name of the intent associated with the utterance.

        Returns:
            Message: A formatted message prompt for classification.
        """
        content = (
            "You are a critic that determines whether a user utterance was written by a human or "
            "generated by a language model.\n\n"
            f"Intent: {intent_name}\n"
            f'Utterance: "{example}"\n\n'
            "Here is an example of a human-written utterance for this intent:\n"
            '"Could you please help me find the nearest coffee shop?"\n\n'
            "Respond in **JSON format** with three keys:\n"
            "- `reasoning`: a short chain-of-thought where you explain your logic\n"
            "- `label`: must be either `human` or `generated`\n"
            "Example:\n"
            "{\n"
            '  "reasoning": "The phrasing includes casual contractions and natural hesitation. The utterance '
            'flows similarly to how a human would speak spontaneously.",\n'
            '  "label": "human",\n'
            "}"
        )
        return Message(role=Role.USER, content=content)

    def is_human(self, utterance: str, intent_name: str) -> bool:
        """Args.

            utterance: The utterance to evaluate.
            intent_name: The associated intent.

        Returns:
            bool: True if classified as human, False otherwise.
        """
        message = self.build_classification_prompt(utterance, intent_name)
        response = self.generator.get_structured_output_sync(
            messages=[message], output_model=CriticResponse, max_retries=self.max_retries
        )
        return response.label == "human"

    async def is_human_async(self, utterance: str, intent_name: str) -> bool:
        message = self.build_classification_prompt(utterance, intent_name)

        response = await self.generator.get_structured_output_async(
            messages=[message], output_model=CriticResponse, max_retries=self.max_retries
        )
        return response.label == "human"
