nodes:
  - node_type: retrieval
    module_type: vector_db
    module_config:
      k: 10
    load_path: .
  - node_type: scoring
    module_type: knn
    module_config:
      weights: uniform
    load_path: .
  - node_type: prediction
    module_config:
      module_type: threshold
      thresh: 0.5
    load_path: .