name: Build and Publish Multi-Version Docs

on:
  push:
    branches:
      - dev
  release:
    types:
      - published
  pull_request:
    branches:
      - dev
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/dev' }}

permissions:
  contents: write

jobs:
  build-docs:
    name: Build Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: setup poetry
        run: |
          curl -sSL https://install.python-poetry.org | python -

      - name: Install pandoc
        run: |
          sudo apt install pandoc

      - name: Install dependencies
        run: |
          poetry install --with docs

      - name: Test documentation build
#        if: github.event_name == 'pull_request' && github.base_ref == 'dev'
        run: |
          echo "Testing documentation build for PR..."
          make test-docs

      - name: build multiversion documentation
        # if: ${{ github.ref == 'refs/heads/dev' }}
        run: |
          make multi-version-docs

#      - name: Build documentation for dev branch
#        # if: github.ref == 'refs/heads/dev'
#        run: |
#          echo "Building docs for dev branch..."
#          poetry run sphinx-build docs/source docs/build/versions/dev

      - name: Deploy to GitHub Pages
        # if: github.event_name != 'pull_request'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ github.token }}
          publish_dir: docs/build/versions
          destination_dir: versions
          keep_files: true
