name: Build and publish docs

on:
  push:
    branches:
    - dev
    - feat/docs_ci
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/dev' }}

permissions:
  contents: write

jobs:
  publish:
    name: build and publish docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: set up python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: setup poetry
        run: |
          curl -sSL https://install.python-poetry.org | python -

      - name: install dependencies
        run: |
          poetry install --with docs

      - name: build documentation
        run: |
          make docs

      - name: save branch name without slashes
        # if: ${{ github.ref != 'refs/heads/dev' }}
        env:
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
        run: |
          BRANCH_NAME=${{ env.BRANCH_NAME }}
          BRANCH_NAME=${BRANCH_NAME////_}
          echo BRANCH_NAME=${BRANCH_NAME} >> $GITHUB_ENV

      - name: save artifact
        # if: ${{ github.ref != 'refs/heads/dev' }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ format('github-pages-for-branch-{0}', env.BRANCH_NAME) }}
          path: docs/build/
          retention-days: 3

      - name: deploy website
        # if: ${{ github.ref == 'refs/heads/dev' }}
        uses: JamesIves/github-pages-deploy-action@v4.6.4
        with:
          branch: gh-pages
          folder: docs/build/html/
          single-commit: True