name: Build and Publish Multi-Version Docs

on:
  push:
    branches:
      - dev
  release:
    types:
      - published
  pull_request:
    branches:
      - dev
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/dev' }}

permissions:
  contents: write

jobs:
  build-docs:
    name: Build Documentation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: setup poetry
        run: |
          curl -sSL https://install.python-poetry.org | python -

      - name: Install pandoc
        run: |
          sudo apt install pandoc

      - name: Install dependencies
        run: |
          poetry install --with docs

      - name: Run tests
        run: |
          echo "Testing documentation build..."
          make test-docs

      - name: Build documentation
        if: ${{ github.ref == 'refs/heads/dev' }}
        run: |
          make docs

      - name: build multiversion documentation
        if: github.event_name == 'release' || github.event_name == 'workflow_dispatch'
        run: |
          make multi-version-docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.event_name == 'release' || github.event_name == 'workflow_dispatch'
        with:
          github_token: ${{ github.token }}
          publish_dir: docs/build/html/versions
          destination_dir: versions
          keep_files: true
