name: test presets

on:
  push:
    branches:
      - dev
  pull_request:

jobs:
  test:
    uses: ./.github/workflows/reusable-test.yaml
    secrets: inherit
    with:
      test_command: pytest -n auto tests/pipeline/test_presets.py
      extras: --extra catboost --extra peft --extra transformers --extra sentence-transformers
