name: Typing
on: [ push, pull_request ]
jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-python@v6
        with:
          python-version: "3.10"

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.10.0"

      - name: Install dependencies
        run: |
          uv lock
          uv sync --group typing --group test --extra catboost --extra peft --extra transformers --extra sentence-transformers --extra openai

      - name: Run mypy
        continue-on-error: true
        run: uv run mypy src/autointent tests
